version: 1.0.{build}
image: Visual Studio 2019
configuration: Debug
platform: Any CPU
#environment:
#  ORG_KEY:
#    secure: UtLhTx5OKGoBoPuIZCXgUg==
#  PROJECT_KEY:
#    secure: N1ZOn6ZWA2ekawtX69IycCxBh2DUhhxwWo8Hf0QyRZw=
#  AUTH_TOKEN:
#    secure: vZvGq83idvZZ4wVZ6pv9AsCvqms5UYtltsd3t9Wkf30xw7GGpbO/W7XUDAVWUJ8w
init:
  - ps: $env:JAVA_HOME = "C:\Program Files\Java\jdk11"
  - ps: $env:JAVA_HOME
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - ps: echo $env:ORG_KEY
  - ps: nuget restore
  - ps: dotnet tool install -g dotnet-sonarscanner
  - ps: dotnet sonarscanner begin /o:"$env:ORG_KEY" /k:"$env:PROJECT_KEY" /v:%APPVEYOR_BUILD_VERSION% /d:sonar.branch.name=%APPVEYOR_REPO_BRANCH% /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$env:AUTH_TOKEN" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="CoverageResults\coverage.opencover.xml"
build_script:
  - ps: dotnet build ZbW.Testing.WpfSample.sln
  - ps: dotnet test ZbW.Testing.WpfSample.Client.IntegrationTests\ZbW.Testing.WpfSample.Client.IntegrationTests.csproj
  - ps: dotnet test ZbW.Testing.WpfSample.Client.UnitTests\ZbW.Testing.WpfSample.Client.UnitTests.csproj
  - ps: dotnet test ZbW.Testing.WpfSample.Libs.IpInfoInterface.IntegrationTests\ZbW.Testing.WpfSample.Libs.IpInfoInterface.IntegrationTests.csproj
after_build:
  - ps: dotnet sonarscanner end /d:sonar.login="$env:AUTH_TOKEN"
artifacts:
  - path: ZbW.Testing.WpfSample.Client\bin\$(configuration)\netcoreapp3.1
    name: ZbW.WpfSample